---
# file: tasks/deploy_client.yml

- name: Clear local backup keypair
  become: no
  openssh_keypair:
    path: "{{ proxmox_local_key_dir }}/{{ ansible_nodename }}"
    size: 4096
    comment: "{{ ansible_nodename }}"
    state: absent
  delegate_to: "localhost"
