---
# file: defaults/main.yml
proxmox_backup_time:
  - cron:
    minute: "{{ 60 | random(seed=inventory_hostname) }}"
    hour: "{{ 7 | random(seed=inventory_hostname) }}"
    day: "*/3"

proxmox_backup_user: "ssh-backup"
proxmox_backup_port: "22"
proxmox_backup_dir: "/vault/backup/proxmox"
proxmox_client_dump_dir: "/var/lib/vz/dump"
proxmox_client_script_dir: "/root/scripts"
proxmox_client_backup_user: "root"
proxmox_client_backup_user_homedir: "/root"
proxmox_client_script_name: "proxmox-backup.sh"
proxmox_local_key_dir: "files/keys"
proxmox_keep: 4
